spring.datasource.url=jdbc:mysql://localhost:3307/Voting_system_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=Anvith
spring.datasource.password=8861102894
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true



springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


springdoc.swagger-ui.operationsSorter=alpha


server.port=8080
blockchain.rpc.url=http://127.0.0.1:7545
blockchain.private.key=0x98f2db27d6ce99be6926cc15f9f312b4d85d9c409e7f2393c44600b4f706055f
contract.address=0x9EE3ca0f95Bb982827C2EE3F911D02b10e231fdC
server.error.include-message=always


